/**
 * @file Automatically generated by barrelsby.
 */

export * from './CoachCategoryFeatured/CoachCategoryFeatured'
export * from './CoachCategoryThumbnail/CoachCategoryThumbnail'
export * from './CoachProfile/CoachProfile.gql'
export * from './CoachProfile/CoachProfile'
