/**
 * @file Automatically generated by barrelsby.
 */

export * from './AboutHow/AboutHow.gql'
export * from './AboutHow/AboutHow'
export * from './AboutServices/AboutServices.gql'
export * from './AboutServices/AboutServices'
export * from './AboutTeam/AboutTeam'
export * from './CoachCategoryCta/CoachCategoryCta.gql'
export * from './CoachCategoryCta/CoachCategoryCta'
export * from './PageIntro/PageIntro'
